-- Create comments table
create table if not exists comments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  paper_id uuid references papers(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table comments enable row level security;

-- Policies
-- 1. Everyone can read comments
drop policy if exists "Comments are viewable by everyone" on comments;
create policy "Comments are viewable by everyone"
  on comments for select
  using ( true );

-- 2. Authenticated users can insert comments
-- Note: Check against auth.uid() which should match user_id (since profiles.id = auth.users.id)
drop policy if exists "Users can insert their own comments" on comments;
create policy "Users can insert their own comments"
  on comments for insert
  with check ( auth.uid() = user_id );

-- 3. Users can delete their own comments
drop policy if exists "Users can delete their own comments" on comments;
create policy "Users can delete their own comments"
  on comments for delete
  using ( auth.uid() = user_id );
