-- Create a table for public profiles using Supabase Auth
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  email text,
  full_name text,
  avatar_url text,
  x_handle text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update their own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for saved papers
create table saved_papers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  paper_id uuid references papers(id), -- CHANGED: bigint -> uuid
  saved_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Create a composite unique constraint to prevent duplicates
  unique(user_id, paper_id)
);

-- Set up RLS for saved_papers
alter table saved_papers enable row level security;

create policy "Users can view their own saved papers."
  on saved_papers for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own saved papers."
  on saved_papers for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own saved papers."
  on saved_papers for delete
  using ( auth.uid() = user_id );

-- Helper to handle new user signup automatically (Optional but recommended)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, username, email)
  values (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url',
    new.raw_user_meta_data->>'username',
    new.email
  );
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if it already exists so we can recreate it
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
